apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api.yaml
  - svc.yaml

nameSuffix: -api

# patches:
#   - target:
#       kind: Service
#       name: svc
#     patch: |-
#       - op: replace
#         path: /spec/ports/0/name
#         value: http-port

patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        creationTimestamp: null
        labels:
          app: api-svc
        name: svc
      spec:
        ports:
        - name: http-port
          port: 8080
          protocol: TCP
          targetPort: 80
        - name: https-port
          port: 443
          protocol: TCP
          targetPort: 8080
        selector:
          app: api-svc
        type: ClusterIP