apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-hello
    name: api
  name: nginx-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-hello
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-hello
        name: api
    spec:
      containers:
      - image: nginxdemos/hello
        name: hello
        resources: {}
status: {}
